### ISSUE TITLE
EPIC - As a teacher, I want to create lessons and save them locally on my computer so that I can send the lesson files to other teachers for them to use.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#1]
This user story is a mismatch of several smaller stories and even repeats previous stories. 

**Acceptance Criteria**
- [ ] Teacher can create lessons for students
- [ ] Teacher can view other teachers works 
- [ ] Teacher can download lessons

**Task**
- [ ] Specify how teachers will see other work
- [ ] Communicate with gallery team
- [ ] Complete user story for lesson creation 
- [ ] Create a consistent database model for lessons to simplify download and integration of external lessons

https://www.figma.com/file/RdtCjnsLTSfhnzFUUk3mOv/Group-9H---Project-17-Teacher-View-and-Lesson-Creation?type=design&node-id=1-2&mode=design&t=BrI0a3fbzSMXk0CX-0
