### ISSUE TITLE
As an online educator, I want a high-level overview of multiple classrooms so that I can manage and navigate through my different online classrooms efficiently.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#10]
**Acceptance Criteria**
- [ ] Teacher can view all/multiple classrooms at a time 
- [ ] Classrooms are represented in card formats with condensed information
- [ ] Information such as class name, meeting times, and number of students should appear
- [ ] Preview of latest lessons are shown 

**Tasks**
- [ ] Create card format/view
- [ ] Connect with database to get necessary information
- [ ] Create hover effect to show which classroom the teacher is currently on
- [ ] Listener event triggered when a card is clicked; switches to individual view of selected classroom
- [ ] Determine how many classrooms can appear on a single page before requiring navigation of list of classrooms

https://www.figma.com/file/RdtCjnsLTSfhnzFUUk3mOv/Group-9H---Project-17-Teacher-View-and-Lesson-Creation?type=design&node-id=1-2&mode=design&t=BrI0a3fbzSMXk0CX-0
