### ISSUE TITLE
As a professor at a University, I want to organize all of the students that I am teaching. I want to decrease the amount of time I spend searching through my class roster to keep track of specific students.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#2]
**Acceptance Criteria**
- [x] Teacher can search for student by name
- [x] Teacher can sort students by name, initial, or password
- [x] Teacher can see the list update when search parameters change
- [x] Search form design matches the websites design

**Tasks**
- [x] Create search form 
- [x] Create sort button
- [x] Listener event to trigger when changes occur in forms
- [x] Design, style, and create aesthetically pleasing front-end 

https://www.figma.com/file/RdtCjnsLTSfhnzFUUk3mOv/Group-9H---Project-17-Teacher-View-and-Lesson-Creation?type=design&node-id=1-2&mode=design&t=BrI0a3fbzSMXk0CX-0
