### ISSUE TITLE
As an in-person teacher, I want to be able to assign lessons to quickly set a lesson to be public for students to observe.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#3]
**Acceptance Criteria**
- [ ] The teacher can set a lesson to be "public" or "private"
- [ ] The teacher can see the progress of students: "not started" "in-progress" "submitted"
- [ ] Dropdown menu/search filter to select a number of classrooms where a lesson will be added to the curriculum of
- [ ] The teacher can select multiple lessons to add to classroom curriculum

**Tasks** 
- [ ] Communicate with student view team about lesson public and private status
- [ ] Communicate with student view team about progress tracking
- [ ] Create form to select lessons
- [ ] Create dropdown menu and search filter for classrooms
- [ ] Add listener to trigger when lessons have been deployed to classrooms

https://www.figma.com/file/RdtCjnsLTSfhnzFUUk3mOv/Group-9H---Project-17-Teacher-View-and-Lesson-Creation?type=design&node-id=1-2&mode=design&t=BrI0a3fbzSMXk0CX-0
