### ISSUE TITLE
As a teacher, I want to be able to see what lessons are assigned or not assigned, to ensure classes have the correct lessons.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#4]
**Acceptance Criteria**
- [ ] Within the individual classroom view, the teacher can see the curriculum of the class
- [ ] Lesson name and short description must be visible
- [ ] Teacher can access specific lesson to ensure that it is the correct version of a lesson
- [ ] Teacher can remove lesson if not correct

**Task**
- [ ] Create front-end curriculum for lesson viewing on the individual classroom page
- [ ] Access the information of lessons to show title and description
- [ ] Create remove button for lessons
- [ ] Make lessons interactable to see detailed view
- [ ] Listener event/state changes implemented to rerender the page

https://www.figma.com/file/RdtCjnsLTSfhnzFUUk3mOv/Group-9H---Project-17-Teacher-View-and-Lesson-Creation?type=design&node-id=1-2&mode=design&t=BrI0a3fbzSMXk0CX-0
