### ISSUE TITLE
As a teacher, I want to be able to quickly navigate through my lessons to find an already created lesson.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#5]
Possibly a match with a previous user story

**Acceptance Criteria**
- [ ] Teacher can interact with a search filter to search for lessons by name
- [ ] Teacher can see the status of a lesson "draft" "ready to publish"
- [ ] Lessons can be sorted by name a-z z-a
- [ ] Lessons can be given tags representing content and can be searched via said tags

**Tasks**
- [ ] Create lesson library frontend
- [ ] Create search form for parameters
- [ ] Create checkbox form for tags
- [ ] Create sort button 
- [ ] Listener dynamically updates whenever a parameter changes
- [ ] Access the database for all lessons created by teacher

https://www.figma.com/file/RdtCjnsLTSfhnzFUUk3mOv/Group-9H---Project-17-Teacher-View-and-Lesson-Creation?type=design&node-id=1-2&mode=design&t=BrI0a3fbzSMXk0CX-0
