### ISSUE TITLE
As an in-person teacher, I want to easily create a new lesson from the dashboard so that I can quickly start planning my lesson.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#6]
**Acceptance Criteria**
- [x] Teacher can have the option of creating a lesson from the home page
- [x] Lesson creation accepts title and description
- [ ] Lesson can be given a deadline date (Optional information from teacher)
- [x] submit button to save 
- [ ] Can restrict the blocks that can be used on the assignment

**Tasks**
- [x] Create front end form
- [x] Create submit button
- [x] Integrate the quick lesson front-end with the dashboard
- [ ] Client-side listener to check when teacher finishes lesson creation
- [ ] Integrate with the model from postgres database
