### ISSUE TITLE
As a team leader, I want a simple mechanism like a “Trash” button to remove students from a classroom with a confirmation prompt to avoid accidental removals.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#7]
**Acceptance Criteria**
- [ ] Teacher can see a trash button appear when hovering over a student in roster page
- [ ] Teacher is prompted with a confirmation message 
- [ ] When pressed "yes", student is removed from roster and thus disappears from it
- [ ] When pressed "no", nothing changes
- [ ] Database is properly updated

**Tasks**
- [ ] Create hover effect on a student account when mouse over
- [ ] Trash button rendered when hover effect finishes
- [ ] Create confirmation message and subsequent buttons
- [ ] Figure out roster model in database or if it even exists
- [ ] Listener event should be triggered when roster changes

https://www.figma.com/file/RdtCjnsLTSfhnzFUUk3mOv/Group-9H---Project-17-Teacher-View-and-Lesson-Creation?type=design&node-id=1-2&mode=design&t=BrI0a3fbzSMXk0CX-0
