### ISSUE TITLE
As an online educator, I want the option to save drafts of my in-progress lessons both manually and automatically so I don’t lose my work.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#8]
**Acceptance Criteria**
- [ ] Teacher can click a save button to save work 
- [ ] Teacher can submit a lesson with one last save
- [x] Automatic saving occurs every 5 minutes
- [ ] Teacher can reaccess the draft lesson and begin work from where they left off

**Tasks**
- [ ] Create front-end button to save work
- [x] Integrate listener to check if allotted time to save has passed
- [ ] Create a "draft" tag for lessons to differentiate publish-ready lessons and drafts
- [ ] Create front-end library of draft lessons for teacher to revisit their work

https://www.figma.com/file/RdtCjnsLTSfhnzFUUk3mOv/Group-9H---Project-17-Teacher-View-and-Lesson-Creation?type=design&node-id=1-2&mode=design&t=BrI0a3fbzSMXk0CX-0
