### ISSUE TITLE
As an in-person teacher, I want to add students to my classroom so I can have all my students accounted for in the system.

### ISSUE THREAD

**Issue by KNPham1337** [Group-9h-Intro-Software-Engineering/Diamond-Project17-9h#9]
**Acceptance Criteria**
- [ ] Teacher can add students to their classroom roster
- [ ] Teacher can add first name and last initial of student
- [ ] Teacher can specify the emoji password for a student
- [ ] The roster should be updated with the new student when teacher submits
- [ ] The database should be updated with new student 

**Tasks**
- [ ] Find out if student roster information is maintained on postgres
- [ ] Find out the model format of a classroom roster
- [ ] Create add button when viewing a roster
- [ ] Create form for student information
- [ ] Create dropdown menu for password emoji

https://www.figma.com/file/RdtCjnsLTSfhnzFUUk3mOv/Group-9H---Project-17-Teacher-View-and-Lesson-Creation?type=design&node-id=1-2&mode=design&t=BrI0a3fbzSMXk0CX-0
